databases:
  - name: questmoney-db
    databaseName: questmoney
    user: questmoney
    plan: free
    region: oregon

services:
  - type: web
    name: questmoney
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: questmoney-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
